declare module 'react-native-fontawesome'
declare module 'react-native-snap-carousel'
declare module 'react-native-expo-image-cache'
declare module 'react-navigation-fluid-transitions'
declare module '*.png'